### ISSUE TITLE
change header colour 

### ISSUE THREAD

**Issue by mianasbat** [UCL/scikit-surgery#101]
Change header colour of http://scikit-surgery.org to yellow as discussed.

**Comment by mianasbat** [comment]
I changed the colour to yellow but it was too bright as given in the picture below.      
So I changed the colour again to a bit cool yellow given in the options. Check changes online http://scikit-surgery.org 
Let me know if it needs changing.

The current one

<img width="1920" alt="Screenshot 2021-01-07 at 15 34 00 (2)" src="https://user-images.githubusercontent.com/2621305/103911346-ceb74f80-50fd-11eb-88c2-eb600d89831a.png">






The yellow colour was looking like below.
<img width="1920" alt="Screenshot 2021-01-07 at 15 23 57 (2)" src="https://user-images.githubusercontent.com/2621305/103911152-9748a300-50fd-11eb-9318-5de3075cb35d.png">

**Comment by thompson318** [comment]
I prefer the 2nd one, brighter and yellower. Thought the text colour on the read the docs button would need changing.

**Comment by mianasbat** [comment]
I changed the colour to yellow. Have a look. It looked a bit too bright to me.
If you guys are happy with yellow colour. I will check how to change the button colour.

**Comment by thompson318** [comment]
I prefer it, but don't have strong feelings about it.

**Comment by mianasbat** [comment]
Okay Matt is also happy with yellow colour so yellow colour it is.
