### ISSUE TITLE
Define Standard Mac Build

### ISSUE THREAD

**Issue by thompson318** [UCL/scikit-surgery#2]
In GitLab by @MattClarkson on Sep 27, 2018, 21:04

Please discuss any requirements for a standard Mac build, then update the wiki page [here](https://weisslab.cs.ucl.ac.uk/WEISS/wiki/wikis/WEISS-Mac) with the final description.

**Comment by thompson318** [comment]
In GitLab by @MattClarkson on Sep 27, 2018, 21:04

changed the description

**Comment by MattClarkson** [comment]
@thompson318 @tdowrick - close?

**Comment by thompson318** [comment]
Yes
