### ISSUE TITLE
Rename SNAPPY?

### ISSUE THREAD

**Issue by thompson318** [UCL/scikit-surgery#50]
In GitLab by @StephenThompson on Feb 5, 2020, 14:50

This is from one of our IPCAI reviewers. How important is the name? Any ideas? 

"The name of the package itself might be confusing for programmers accustomed to using Google's open source Snappy compression library. Info about this SNAPPY is actually difficult to find through your regular search engine."

@MattClarkson , @ThomasDowrick , @MianAhmad

**Comment by thompson318** [comment]
In GitLab by @MattClarkson on Feb 5, 2020, 18:12

I don't mind at all..... er .... but Im useless at branding.

**Comment by thompson318** [comment]
In GitLab by @ThomasDowrick on Feb 6, 2020, 20:50

We could just use the scikit-surgery name instead of SNAPPY? It is more informative anyway and we should avoid clashing with existing projects if we're going to start publicising more widely.

**Comment by thompson318** [comment]
In GitLab by @MattClarkson on Feb 7, 2020, 06:16

That was the best I thought of on the way home. We are already using up that namespace anyway.

**Comment by thompson318** [comment]
In GitLab by @MattClarkson on Mar 16, 2020, 11:17

I like the idea of scikit-surgery, because we have used that for all pypi libraries, so that is our defacto externally facing name. It also indicates the application area (surgery), and the naming convention tells us about its use of standard python libraries.

But it sure sounds more ugly than SNAPPY.

But if we are avoiding SNAPPY due to name clash, then I can't think of a better option than scikit-surgery. So, I vote for that.

**Comment by thompson318** [comment]
In GitLab by @MianAhmad on Mar 16, 2020, 11:23

Thats what I was thinking, if we dont like scikit-surgery then what about all other packages which starts with scikit-?     

Scikit-surgery doesn't look to bad to me. Also there may not be many options available of one word name.     

SNAPPY as one name (as acronym) is nice but when it is written in full then it is not too nice in my view.

**Comment by thompson318** [comment]
In GitLab by @StephenThompson on Mar 17, 2020, 10:17

[snappy_ipcai_diff.pdf](/uploads/ecdf98ca0b564dbc57220768e7e15346/snappy_ipcai_diff.pdf)

I've done a minimal change to the snappy paper, just doing a find and replace on SNAPPY to scikit-surgery where relevant. It seems feasible. I don't know if IJCARS will allow us to do it, but I don't think there's any change to scientific content so I imagine they would. It raises the question of whether we should capitilise it, scikit-surgery looks a bit weird at the start of a sentence? 

Should we retain a reference to the "SNAPPY project" of which scikit-surgery forms a part, or should we just go all out scikit-surgery? 

Any thoughts please.

**Comment by thompson318** [comment]
In GitLab by @MianAhmad on Mar 17, 2020, 11:07

I believe it would be nice to mention that SNAPPY was the internal code name of the project.

**Comment by MattClarkson** [comment]
Lets close this. In effect... its done.
