### ISSUE TITLE
Move SNAPPY libraries to github

### ISSUE THREAD

**Issue by thompson318** [UCL/scikit-surgery#51]
In GitLab by @StephenThompson on Feb 5, 2020, 14:53

This is from one of our IPCAI reviewers. Could we move the core opensource libaries to github to make it easier for people to contribute?

"Gitlab isolates your efforts from the rest of the world. Currently, it does not even seem possible to sign up at https://weisslab.cs.ucl.ac.uk/. Hosting on github would increase visibility and willingness of people to submit bug reports or contribute. If you must host your own repository then at least host an official github mirror to avoid cropping up of unofficial forks."

@MattClarkson @ThomasDowrick @MianAhmad

**Comment by thompson318** [comment]
In GitLab by @ThomasDowrick on Feb 5, 2020, 15:38

Seems a fair point.... If we want people outside UCL to use it we need to have a GitHub presence.

**Comment by thompson318** [comment]
In GitLab by @MianAhmad on Feb 5, 2020, 15:58

Will we need to set pipeline with github?

**Comment by thompson318** [comment]
In GitLab by @ThomasDowrick on Feb 5, 2020, 16:46

If we only mirror to GitHub then no, but if we used GitHub as the main host we'd have to fiddle around with it.

It seems it is possible to use a gitlab runner for GitHub projects https://docs.gitlab.com/ee/ci/ci_cd_for_external_repos/github_integration.html but it probably isn't a good idea to use our own servers for testing a publicly hosted project.

In either case some of the stuff we'd have to keep on our own runners for GPU support.

**Comment by thompson318** [comment]
In GitLab by @MattClarkson on Feb 5, 2020, 18:01

Im Happy to move to Github. Just need to discuss testing.

**Comment by thompson318** [comment]
In GitLab by @ThomasDowrick on Feb 6, 2020, 20:56

I gathered some opinion at RSLondon today about what we could do with this. The consensus seemed to be to that we could move to GitHub and still use our existing runners for testing. People could then fork the repo to make changes, and we have control over what is merged back into our branch.

**Comment by thompson318** [comment]
In GitLab by @ThomasDowrick on Feb 7, 2020, 09:14

Any libraries that don't use VTK/Qt/GPU could use Travis or GitHub CI, but I think doing a mix and match approach is probably more hassle than just keeping everything on our own runners.

**Comment by thompson318** [comment]
In GitLab by @StephenThompson on Feb 11, 2020, 13:55

Sounds like we all agree in principal? We should aim to get this done before publication of the IPCAI paper. I don't think there's time to do it before I resubmit on Thursday, but hopefully I can slip it into the paper once it hits the editors.

**Comment by thompson318** [comment]
In GitLab by @ThomasDowrick on Feb 11, 2020, 13:58

I looked into it and we can follow [this](https://docs.gitlab.com/ee/ci/ci_cd_for_external_repos/) guide to set up the GitHub<->GitLab link. I think we'll have to modify our gitlab configuration on the server, as if you try and do it now the 'CI/CD For External Repo' option isn't there.

![image](/uploads/82e5ece864de38a54bd2faecc2523816/image.png)

**Comment by thompson318** [comment]
In GitLab by @MattClarkson on Feb 11, 2020, 13:59

hold on. Is it possible we'd need the enterprise version? i.e. pay for it. We only have the community free version? Or did I miss something?

**Comment by thompson318** [comment]
In GitLab by @ThomasDowrick on Feb 11, 2020, 14:10

er..... yes. It seems you're right.

**Comment by thompson318** [comment]
In GitLab by @MianAhmad on Mar 5, 2020, 10:22

I wonder if github education program is equivalent to enterprise github. I am using it to host many private repos then the free tier offer. It is offered  for two years and students and staff has to fill the form on this page [https://education.github.com/discount_requests/new](https://education.github.com/discount_requests/new).      

The following image shows that I am using it since 2017.      
![Screenshot_2020-03-05_at_10.16.56](/uploads/6b66a5229dcb303cd64732ad36921e25/Screenshot_2020-03-05_at_10.16.56.png)

**Comment by thompson318** [comment]
In GitLab by @StephenThompson on Mar 16, 2020, 10:28

I want to get this sorted before the Snappy IPCAI paper get's published, so that the links in it are right. I've just gone through the paper and the only link to weisslab is the wiki, (https://weisslab.cs.ucl.ac.uk/WEISS/PlatformManagement/SNAPPY). So my main priority would be to migrate the wiki to github. We could use UCL's github group, so something like https://github.com/UCL/SNAPPY. That wouldn't have any issues with CI testing yet. Does that sound OK?

**Comment by thompson318** [comment]
In GitLab by @MattClarkson on Mar 16, 2020, 10:32

yep.... or the alternative UCL/scikit-surgery?

Can you remind me what we decided about renaming?

**Comment by thompson318** [comment]
In GitLab by @StephenThompson on Mar 16, 2020, 10:37

I don't think we came to a decision on renaming. I didn't think scikit-surgery was catchy enough, though it is more searchable. From a practical point of view changing the name would be a substantial edit of the paper, as opposed to changing a link.

**Comment by thompson318** [comment]
In GitLab by @ThomasDowrick on Mar 16, 2020, 10:52

True that scikit-surgery isn't super catchy, but if we're agreed that we shouldn't use SNAPPY too much publically because it clashes with other names, then we should probably change it sooner rather than later. Given that we haven't thought of any better names in the 2ish years we've been working on it, then I'd say we're unlikely to think of anything else.

Shall we take a vote on it?

**Comment by thompson318** [comment]
In GitLab by @StephenThompson on Mar 16, 2020, 11:08

Let me try doing a find and replace on the paper, I'll just change SNAPPY to to scikit-surgery and see what it does. I will try it out tomorrow. We should move discussion on renaming back to issue #50

**Comment by thompson318** [comment]
In GitLab by @StephenThompson on Apr 3, 2020, 11:33

UCL appears to have a Azure account, so could use that for CI from github rather than travis or appveyor?

**Comment by thompson318** [comment]
In GitLab by @MattClarkson on Apr 3, 2020, 11:38

we can certainly host on github.com/UCL/<whatever>

but Im not sure what Azure provides ... is it Windows/Linux/Mac. The only reason Im suggesting Travis/Appveyor, is Travis=Linux/Mac and Appveyor=Windows, but I think travis now has all 3.

@ThomasDowrick - can you clarify?

**Comment by thompson318** [comment]
In GitLab by @StephenThompson on Apr 3, 2020, 11:45

I googled "tox azure" and got this. It implies it covers our target platforms and can be set up to use tox more easily than travis at least, but I really don't know.

https://github.com/tox-dev/azure-pipelines-template

**Comment by thompson318** [comment]
In GitLab by @MattClarkson on Apr 3, 2020, 11:46

I don't know if @ThomasDowrick is available (Childcare), but you could as on RITS slack channel. Jonathan Cooper would know.

**Comment by thompson318** [comment]
In GitLab by @ThomasDowrick on Apr 3, 2020, 12:28

I haven't used the Azure stuff much - I think asking RITS might be a good idea as I know they have used it a bit and can give some feedback on it (Some of it wasn't great if I recall...)

**Comment by thompson318** [comment]
In GitLab by @ThomasDowrick on Apr 3, 2020, 12:30

I think we can @DavidPerez-Suarez @JonathanCooper - have either of you used Azure Pipelines for CI before?

In brief, we're moving some of our repos from here to GitHub and are thinking about where to host CI. Since UCL has an Azure service/account, there might be some additional features we get?

**Comment by thompson318** [comment]
In GitLab by @JonathanCooper on Apr 6, 2020, 09:28

Mose was looking into CI options along with David, so I'll defer to them!

**Comment by thompson318** [comment]
In GitLab by @MianAhmad on Apr 6, 2020, 10:19

So I did some search on weekend and most of the cloud dont provide Mac VM because according to the Apple license Mac OS can only be installed on Apple hardware. Since cloud uses all VM's therefore cant give you apple. (May be some illegal ways are available to install apple on VM but not legal).     

Some clouds put a mac hardware to provide mac OS to customers but they are very expensive.

**Comment by thompson318** [comment]
I've moved the wiki from 
https://weisslab.cs.ucl.ac.uk/WEISS/PlatformManagement/SNAPPY to https://github.com/UCL/scikit-surgery/wiki
The platform related issues have moved with it.

I've also moved the minimal code from 
https://weisslab.cs.ucl.ac.uk/WEISS/SoftwareRepositories/SNAPPY/scikit-surgery
to https://github.com/UCL/scikit-surgery/ so now we have code and wiki in the same place. The second move involved leaving the 4 raised issues on scikit-surgery behind. but these were not very interesting and in any case remain on weisslab for anyone interested.

**Comment by tdowrick** [comment]
**Moving scikit-surgerycore**

- [x] Files/git history moved
- [x] Issues moved 
- [x] CI working for Mac/Windows/Linux, using GitHub Actions 
- [ ] Old CI files removed
- [ ] Test deploy to PyPI

**Comment by tdowrick** [comment]
@thompson318 @MattClarkson  should we do something like the above for each repo when we move it? Any other checkboxes to add?

**Comment by thompson318** [comment]
Looks reasonable, thanks. Could add one to check that read the docs is working, and maybe that all relevant links have been changed to github.

**Comment by tdowrick** [comment]
**Moving scikit-surgeryimage**

- [x] Files/git history moved
- [x] Issues moved 
- [ ] CI working for Mac/Windows/Linux, using GitHub Actions
- [ ] Old CI files removed
- [ ] Test deploy to PyPI 
- [x] Update read the docs
- [ ] Relevant links changed to point to GitHub rather than GitLab

Haven't got GitHub CI to work on Linux yet.

**Comment by tdowrick** [comment]
**scikit-surgerynditracker**

- [x] Files/git history moved
- [x] Issues moved 
- [x] CI working for Mac/Windows/Linux, using GitHub Actions
- [x] Old CI files removed
- [x] Badges updated
- [x] Test deploy to PyPI 
- [x] Update read the docs
- [x] Relevant links changed to point to GitHub rather than GitLab
- [x] Changes merged

**Comment by tdowrick** [comment]
**scikit-surgeryarucotracker**

- [x] Files/git history moved
- [x] Issues moved 
- [x] CI working for Mac/Windows/Linux, using GitHub Actions
- [x] Old CI files removed
- [x] Badges updated
- [x] Add PYPI_API_TOKEN as Secret and Test deploy to PyPI 
- [x] Update read the docs
- [x] Relevant links changed to point to GitHub rather than GitLab

**Comment by thompson318** [comment]
scikit-surgerybard

- [ ] Files/git history moved
- [ ] Issues moved
- [ ] CI working for Mac/Windows/Linux, using GitHub Actions
- [ ] Old CI files removed
- [ ] Badges updated
- [ ] Add PYPI_API_TOKEN as Secret and Test deploy to PyPI
- [ ] Update read the docs
- [ ] Relevant links changed to point to GitHub rather than GitLab
- [ ] Changes merged

**Comment by thompson318** [comment]
scikit-surgerybard

- [ ] Files/git history moved
- [ ] Issues moved
- [ ] CI working for Mac/Windows/Linux, using GitHub Actions
- [ ] Old CI files removed
- [ ] Badges updated
- [ ] Add PYPI_API_TOKEN as Secret and Test deploy to PyPI
- [ ] Update read the docs
- [ ] Relevant links changed to point to GitHub rather than GitLab
- [ ] Changes merged

**Comment by thompson318** [comment]
sciikit-surgeryvtk
- [ ] Files/git history moved
- [ ] Issues moved
- [ ] CI working for Mac/Windows/Linux, using GitHub Actions
- [ ] Old CI files removed
- [ ] Badges updated
- [ ] Add PYPI_API_TOKEN as Secret and Test deploy to PyPI
- [ ] Update read the docs
- [ ] Relevant links changed to point to GitHub rather than GitLab
- [ ] Changes merged

**Comment by tdowrick** [comment]
I can look at the CI for vtk - can you make me an admin on the repo?

**Comment by thompson318** [comment]
I'm just transfering files/issues. I think it will take about two hours.

**Comment by thompson318** [comment]
OK, you should have admin access now.

**Comment by tdowrick** [comment]
Thanks. CI definitely more fiddly with this library, but I'll keep working on it.

**Comment by JonathanCooper** [comment]
Hey folks!  Just wanted to flag to you that you are tagging the wrong Jonathan Cooper!

**Comment by tdowrick** [comment]
**scikit-surgeryspeech**

- [x] Files/git history moved
- [x] Issues moved 
- [ ] CI working for Mac/Windows/Linux, using GitHub Actions
- [ ] Old CI files removed
- [ ] Badges updated
- [ ] Add PYPI_API_TOKEN as Secret and Test deploy to PyPI 
- [ ] Update read the docs
- [ ] Relevant links changed to point to GitHub rather than GitLab
- [ ] Changes merged

**Comment by tdowrick** [comment]
For reference, [this](https://github.com/piceaTech/node-gitlab-2-github) is the tool we've been using to transfer issues between Gitlab/Github. Runs relateively slowly (can take several hours) but is simple enough to run.

**Comment by tdowrick** [comment]
**scikit-surgerytf**

- [x] Files/git history moved
- [x] Issues moved 
- [ ] CI working for Mac/Windows/Linux, using GitHub Actions
- [x] Old CI files removed
- [x] Badges updated
- [ ] Add PYPI_API_TOKEN as Secret and Test deploy to PyPI 
- [ ] Update read the docs
- [ ] Relevant links changed to point to GitHub rather than GitLab
- [ ] Changes merged

**Comment by tdowrick** [comment]
@thompson318 Have you been your process for removing project from weisslab? Are you archiving them or just deleting?

**Comment by thompson318** [comment]
I haven't been doing either yet, I just changed the readme to say "XXX had moved to github please visit <link>". Then disabling everything in the settings. Have a look at surgerycore on weisslab for an example. So if someone is looking for it on weisslab they will still be able to find it and get redirected. I didn't want them to just disappear from weisslab straight away.

**Comment by tdowrick** [comment]
Thanks - I'll do the same.

**Comment by tdowrick** [comment]
**scikit-surgerybk**

- [x] Files/git history moved
- [x] Issues moved 
- [x] CI working for Windows/Linux, using GitHub Actions. (Skipping Mac CI, as there are issues with GPU)
- [x] Old CI files removed
- [x] Badges updated
- [x] Add PYPI_API_TOKEN as Secret and Test deploy to PyPI 
- [x] Update read the docs
- [x] Relevant links changed to point to GitHub rather than GitLab
- [x] Changes merged

**Comment by tdowrick** [comment]
I have finished surgeryvtk and surgerytf. In both cases there were issues with getting the Mac CI to run correctly. We decided it was better to skip these, as Linux/Windows CI working and we have been able to test locally on Mac, rather than spend time trying to resolve.

**Comment by tdowrick** [comment]
**scikit-surgeryutils**

- [x] Files/git history moved
- [x] Issues moved 
- [x] CI working for Windows/Linux, using GitHub Actions. (Skipping Mac CI, as there are issues with GPU)
- [x] Old CI files removed
- [x] Badges updated
- [x] Add PYPI_API_TOKEN as Secret and Test deploy to PyPI 
- [x] Update read the docs
- [x] Relevant links changed to point to GitHub rather than GitLab
- [x] Changes merged

**Comment by MattClarkson** [comment]
@thompson318 - most of this issue is done? close?

**Comment by thompson318** [comment]
There's a couple of things to do on snappysonic first. (see list above)

**Comment by thompson318** [comment]
sciikit-surgerytrackervisualisation
- [] Files/git history moved
- [] Issues moved
- [] CI working for Mac/Windows/Linux, using GitHub Actions
- [] Old CI files removed
- [] Badges updated
- [] Add PYPI_API_TOKEN as Secret and Test deploy to PyPI
- [] Update read the docs
- [] Relevant links changed to point to GitHub rather than GitLab
- [] Changes merged

**Comment by thompson318** [comment]
**sciikit-surgery-evaluation**

- [ ] Files/git history moved
- [ ] Issues moved
- [ ] CI working for Mac/Windows/Linux, using GitHub Actions
- [ ] Old CI files removed
- [ ] Badges updated
- [ ] Add PYPI_API_TOKEN as Secret and Test deploy to PyPI
- [ ] Update read the docs
- [ ] Relevant links changed to point to GitHub rather than GitLab
- [ ] Changes merged

**Comment by thompson318** [comment]
**SNAPPY Tutorial 01**

- [ ] Files/git history moved
- [ ] Issues moved
- [ ] CI working for Mac/Windows/Linux, using GitHub Actions
- [ ] Old CI files removed
- [ ] Badges updated
- [ ] Add PYPI_API_TOKEN as Secret and Test deploy to PyPI
- [ ] Update read the docs
- [ ] Relevant links changed to point to GitHub rather than GitLab
- [ ] Changes merged

**Comment by thompson318** [comment]
**SNAPPY Tutorial 02**

- [ ] Files/git history moved
- [ ] Issues moved
- [ ] CI working for Mac/Windows/Linux, using GitHub Actions
- [ ] Old CI files removed
- [ ] Badges updated
- [ ] Add PYPI_API_TOKEN as Secret and Test deploy to PyPI
- [ ] Update read the docs
- [ ] Relevant links changed to point to GitHub rather than GitLab
- [ ] Changes merged
