### ISSUE TITLE
Is the link correct for the list of common issues?

### ISSUE THREAD

**Issue by mianasbat** [UCL/scikit-surgery#68]
The link for the list of common issues point to new page on project wiki in readme.rst file.    
Check on page https://github.com/UCL/scikit-surgery where it says [Please check list of common issues.]    
I believe this link should point to the issues page i.e https://github.com/UCL/scikit-surgery/issues      

@tdowrick @thompson318 @MattClarkson

**Comment by thompson318** [comment]
Yes, it would make more sense to point to the github issues.

**Comment by mianasbat** [comment]
The link is updated to the correct webpage i.e. https://github.com/UCL/scikit-surgery/issues
