### ISSUE TITLE
Do we need to have internal PyPI column?

### ISSUE THREAD

**Issue by mianasbat** [UCL/scikit-surgery#69]
The main table on project [wiki page](https://github.com/UCL/scikit-surgery/wiki) shows internal PiPY column and in all cases its value is either N/A or Null. In that case would it make sense to keep this column?     

I remember setting up a test PyPI server internally on my mac but it wasn't used. So is it our requirement to have an internal PyPI server? if not then why keep the column?

@tdowrick @thompson318 @MattClarkson

**Comment by thompson318** [comment]
I think we can remove it.

**Comment by mianasbat** [comment]
The internal PyPI column is removed.
