### ISSUE TITLE
Get domain name

### ISSUE THREAD

**Issue by MattClarkson** [UCL/scikit-surgery#71]
scikit-surgery.org

redirect to: https://scikit-surgery.readthedocs.io/en/latest/?badge=latest

**Comment by mianasbat** [comment]
Ron has been requested to register a domain name scikit-surgery.org for us and redirect the URL to above URL.

**Comment by mianasbat** [comment]
Sent a reminder to Ron on Thursday but no response till now. I will update when I hear anything from him.

**Comment by mianasbat** [comment]
Sent a reminder to Ron about domain name on teams.

**Comment by mianasbat** [comment]
The domain name 'scikit-surgery.org' is registered.
