### ISSUE TITLE
Dev Meeting: 22/10/2020

### ISSUE THREAD

**Issue by MattClarkson** [UCL/scikit-surgery#77]
Present: @MattClarkson @mianasbat @tdowrick 
Apols: @thompson318 

Things closed since last week:
* #64 
* #67 

Actions:
* #71 - domain name
* #71 - updating all scikit-surgery sub-projects to be compliant with new documentation standard. @mianasbat to help @tdowrick 
* #73 - Need nice intro for scikit-surgery, as landing page dull
* #75 - To promote scikit-surgery, new tutorials? 
* #76 - Discuss new directions?

Discussed:

* scikit-surgery is top level project to amalgamate docs
* therefore we can remove CI/build, as there's no code, so #67 fixed.
* actions as above. 
* Matt/Tom worked on scikit-surgerysurface match, fixing up ICP based registration. New surface based registration tool in SmartLiver project.

**Comment by MattClarkson** [comment]
Decided to update scikit-surgery docs once per month, or on any major release, rather than try to be too clever.

**Comment by tdowrick** [comment]
I have updated documentation for scikit-surgeryutils, surfacematch, torch and tf.

I've also added a list of all current tutorials (that I could find) to the scikit-surgery README, which is also included in the readthedocs page.

**Comment by tdowrick** [comment]
For reference, this is how to manually update all submodules, to pull in any changes to the documentation:

```
git clone https://github.com/UCL/scikit-surgery --recursive
git submodule update --remote --merge
git add -u
git commit -m "Updating docs"
git push
```

**Comment by thompson318** [comment]
Should also list surgery*tracker and surgery speech on the list of packages

**Comment by tdowrick** [comment]
I'm updating the documentation for them at the moment, then can add to the main list.

Do you own the Readthedocs project for nditracker, and can you add me to it?

**Comment by thompson318** [comment]
Thanks. I've added you as maintainer to a bunch of my readthedocs projects.
