### ISSUE TITLE
Version on PyPI needs updating!

### ISSUE THREAD

**Issue by mianasbat** [UCL/scikit-surgery#79]
The available version on PyPI shows the build failing and we probably needs to push new version of repo to PyPI server to reflect the latest updates.

**Comment by tdowrick** [comment]
Since we're now using this as a documentation only repository, we can probably remove the entry from PyPI as we don't want people to install it.

**Comment by mianasbat** [comment]
I guess better would be to push a new package even if only documentation instead of deleting it. BECAUSE

On searching scikit-surgery the first link appears for PIPy server as below
<img width="926" alt="Screenshot 2020-10-30 at 11 20 06" src="https://user-images.githubusercontent.com/2621305/97699532-35870f80-1aa2-11eb-80cd-8e993b0729aa.png">

And now after delete on clicking that link I get 404 error as below

<img width="907" alt="Screenshot 2020-10-30 at 11 20 15" src="https://user-images.githubusercontent.com/2621305/97699587-4afc3980-1aa2-11eb-9e1d-1b0de5ddea53.png">

**Comment by tdowrick** [comment]
I imagine this will disappear from Google rankings fairly quickly, so might be OK to leave it.

**Comment by mianasbat** [comment]
Okay yes true.
I think it also makes sense to not have documentation only package on PIPy server. Right?
