### ISSUE TITLE
Links need updating

### ISSUE THREAD

**Issue by mianasbat** [UCL/scikit-surgery#82]
The two links on wiki page shown in the following picture needs updating. Details given below.

<img width="1141" alt="Screenshot 2020-11-02 at 12 59 22" src="https://user-images.githubusercontent.com/2621305/97870793-5a31f000-1d0b-11eb-9e47-cf9b1bc33fa6.png">
     

SciKit-Surgery Tutorial 01 link needs updating from https://weisslab.cs.ucl.ac.uk/WEISS/SoftwareRepositories/SNAPPY/SNAPPYTutorial01 to https://github.com/UCL/scikit-surgerytutorial01       

SciKit-Surgery Tutorial 02 link needs updating from  https://weisslab.cs.ucl.ac.uk/WEISS/SoftwareRepositories/SNAPPY/snappytutorial02 to https://github.com/UCL/scikit-surgerytutorial02

SciKit-Surgery Workshop 01 link is pointing to a blank project.

**Comment by thompson318** [comment]
fixed on wiki

**Comment by mianasbat** [comment]
Thanks @thompson318 for fixing, working fine now.
