### ISSUE TITLE
ROS Examples

### ISSUE THREAD

**Issue by tdowrick** [UCL/scikit-surgery#83]
* How to use scikit-surgery with ROS
* Node that takes liver image as input, and returns segmented output
* Which other ROS nodes do IGS stuff?

@MattClarkson @thompson318 @mianasbat

**Comment by tdowrick** [comment]
I've made a start on this, but it seems that ROS only officialy support Python 2.7. It is possible to configure it for Python 3, but it is somewhat involved and I don't think we could assume that a user would be able to do it for the purposes of a tutorial.

Some of the packages will work with Pytohn 2.7, but tensorflow/torch etc, or any of the C++ built libraries would probably cause some issues.

**Comment by thompson318** [comment]
surgery-nditracker  should work with py27. So could so a basic tracking source. Though is ros already has nodes for ndi I'm not sure who'd use it.

**Comment by tdowrick** [comment]
ROS 2.0 does support Python 3, but my (limited) understanding is that ROS 1 is still the more widely used version.

However, for the purposes of give some brief examples of how scikit-surgery can work with ROS, using 2.0 is probably fine, especially if we can then show features that we can't if we are limited to Python 2.7.

**Comment by thompson318** [comment]
I agree it makes sense to use ROS 2.0.

**Comment by tdowrick** [comment]
I've added a little chessboard detection example/tutorial to demonstrate compatibility with ROS2, which I've also added to the list of tutorials on the main page.

https://scikit-surgery.readthedocs.io/en/latest/ros.html

**Comment by tdowrick** [comment]
Closing, as we have one example up. Can create new issues if there are specific things to implement.
