### ISSUE TITLE
Create SciKit-Surgery home page on github pages

### ISSUE THREAD

**Issue by MattClarkson** [UCL/scikit-surgery#84]
And ask Ron to point URL at it.

**Comment by mianasbat** [comment]
I added the first draft http://github-pages.ucl.ac.uk/scikit-surgery/ 
Branch name is web. 

I changed the default header colour from blue-green as in [deepreg.net](deepreg.net) to red-orange to make it a bit different.

I also added some initial contents mentioned on [issue 73](https://github.com/UCL/scikit-surgery/issues/73).

Please comment/feedback.

@MattClarkson @thompson318 @tdowrick

**Comment by tdowrick** [comment]
I would add links to the documentation and the github repo right at the top, like they have done with deepreg, but otherwise the layout looks good.

Guess we should try and come up with a logo?

**Comment by thompson318** [comment]
I agree with Tom, it needs some links at the top. You could try using WEISS blue (0.0, 0.384, 0.490) rather than orange for branding. The hunt is on for a logo.

**Comment by mianasbat** [comment]
Thanks for the feedback.
I will add the button-link for documentation.
For github button, actually I spent some time to disable it because in deepreg case, they have one repo to point to but in our case where will we point it to?

**Comment by mianasbat** [comment]
"Read the docs" button added to the page. http://github-pages.ucl.ac.uk/scikit-surgery/

**Comment by mianasbat** [comment]
http://scikit-surgery.org is now functional and directed to http://github-pages.ucl.ac.uk/scikit-surgery/

**Comment by mianasbat** [comment]
I have also requested to Ron for SSL license for scikit-surgery.org

**Comment by mianasbat** [comment]
This issue could also be closed because the home page is up and running using github pages.
@MattClarkson
