### ISSUE TITLE
SSL certificate for scikit-surgery.org

### ISSUE THREAD

**Issue by mianasbat** [UCL/scikit-surgery#87]
Request and follow with Ron for SSL license for scikit-surgery.org website.

**Comment by mianasbat** [comment]
Sent a request email to Ron to buy ssl license for our domain scikit-surgery.org.

**Comment by MattClarkson** [comment]
We think we don't need this, as once redirected, the destination site has correct SSL.

**Comment by mianasbat** [comment]
So you were right, confirmed :)

Ron has updated the redirect to make it non persistent. 
No more insecure and no need of ssl all is good now
