### ISSUE TITLE
list of publications for home page 

### ISSUE THREAD

**Issue by mianasbat** [UCL/scikit-surgery#89]
Is there any list of publications associated with scikit-surgery/SNAPPY which I can use to add contents to publications section on http://scikit-surgery.org page.

@MattClarkson @thompson318 @tdowrick

**Comment by thompson318** [comment]
Thompson S, Dowrick T, Ahmad M, et al. SciKit-Surgery: compact libraries for surgical navigation. International Journal of Computer Assisted Radiology and Surgery. 2020 Jul;15(7):1075-1084. DOI: 10.1007/s11548-020-02180-5. 
[](url https://doi.org/10.1007/s11548-020-02180-5)
[](url https://img.shields.io/badge/Cite-SciKit--Surgery-informational)

**Comment by thompson318** [comment]
Thompson S, Dowrick T, Xiao G, et al. SnappySonic: An Ultrasound Acquisition Replay Simulator. Journal of Open Research Software. 2020 ;8(1):8. DOI: 10.5334/jors.289. 
http://doi.org/10.5334/jors.289
https://img.shields.io/badge/DOI-10.5334%2Fjors.289-blue

**Comment by thompson318** [comment]
Thompson, S; Dowrick, T; Ahmad, M; Opie, J; Clarkson, M; (2021) Are fiducial registration error and target registration error correlated? SciKit-SurgeryFRED for teaching and research. In: (Proceedings) SPIE Medical Imaging Image-Guided Procedures, Robotic Interventions, and Modeling. SPIE (In press). 
https://discovery.ucl.ac.uk/id/eprint/10112339/

**Comment by mianasbat** [comment]
The above three publications have been added to the publications section of http://scikit-surgery.org/.

**Comment by thompson318** [comment]
Thanks Mian. On the first two can you remove the links to https://img.shields.io? They are just handy badges that I've added to a few of the repositories.

**Comment by mianasbat** [comment]
I have removed the badges. Thanks for checking. 
The updates are reflected usually after 5 minutes.
