### ISSUE TITLE
animation to go on scikit-surgery.org webpage

### ISSUE THREAD

**Issue by mianasbat** [UCL/scikit-surgery#90]
Could you please share any candidate image/git/animation that I could add to the scikit-surgery.org page.

You can share the page link if the object is not easy to share. 

E.g. a couple of animation I know are 

https://github.com/UCL/scikit-surgerytutorial02
https://scikit-surgerytutorial01.readthedocs.io/en/latest/

@MattClarkson @thompson318 @tdowrick

**Comment by thompson318** [comment]
There's a few videos and a gif on the docs page under applications. 
https://scikit-surgery.readthedocs.io/en/latest/?badge=latest

I'm not sure we want to put too many animations on the main page. First and foremost it must be easy to navigate. Animations may distract from that.?

**Comment by mianasbat** [comment]
If no animations need to go on the scikit-surgery.org page then we can close this issue.
@MattClarkson
