### ISSUE TITLE
Twitter account for scikit-surgery

### ISSUE THREAD

**Issue by mianasbat** [UCL/scikit-surgery#92]
I believe it will be nice to have an official twitter account about scikit-surgery. Since scikit-surgery is growing it will be nice to tweet about new version of library or any updates and also to have a place which people can follow.

@MattClarkson @thompson318 @tdowrick

**Comment by tdowrick** [comment]
We discussed briefly in SNAPPY meeting.

In principle, a good idea, but unless there is someone specifcally allocated to operating the account it might remain unused. In the meantime we can flag anything of note to the main WEISS/Med Phys accounts.

**Comment by mianasbat** [comment]
Not needed for now.
