### ISSUE TITLE
Change header colour

### ISSUE THREAD

**Issue by mianasbat** [UCL/scikit-surgery#96]
Change the colour of the header of scikit-surgery.org to see how logo looks with other backgrounds.

**Comment by mianasbat** [comment]
I have changed the header colour to grey. For comparison I took before and after images :)     
Let me know what do you guys think.       
The new one can also be seen live on http://scikit-surgery.org       


OLD
<img width="1920" alt="Screenshot 2020-12-10 at 10 04 15" src="https://user-images.githubusercontent.com/2621305/101757957-b2f56500-3acf-11eb-8ce5-cb4fd5320a19.png">


NEW
<img width="1920" alt="Screenshot 2020-12-10 at 10 09 13" src="https://user-images.githubusercontent.com/2621305/101758074-d1f3f700-3acf-11eb-933c-ced20d786db7.png">




@MattClarkson @thompson318 @tdowrick

**Comment by tdowrick** [comment]
Looks good to me

**Comment by mianasbat** [comment]
It is decided to keep the grey header colour in SNAPPY meeting on 10 December. 
This issue can be closed now.
