### ISSUE TITLE
Logo not rendering properly on firefox ubuntu

### ISSUE THREAD

**Issue by mianasbat** [UCL/scikit-surgery#98]
It renders a bit weird for me on Firefox (Ubuntu), Chrome is fine, see attached screenshot.        

![screenshot](https://user-images.githubusercontent.com/2621305/101759593-b38efb00-3ad1-11eb-861e-b85bd7fa4f24.png)

**Comment by thompson318** [comment]
Commit 52aa253 didn't seem to make any difference.

**Comment by mianasbat** [comment]
@thompson318   
After I made the logo responsive in issue #95, is this issue not fixed?
Can you check the live webpage now and see how it behave on both browsers? thanks.

**Comment by thompson318** [comment]
No, still broken for me.

**Comment by mianasbat** [comment]
@thompson318    
I have merged the changes. Give it a try after few minutes.
